# Generated by Django 4.1.4 on 2023-02-13 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        auto_created=True,
                        default=datetime.datetime(
                            2023,
                            2,
                            20,
                            19,
                            44,
                            13,
                            211192,
                            tzinfo=datetime.timezone.utc,
                        ),
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todo_app.list"
                    ),
                ),
            ],
        ),
    ]
